Learning rate, betas, eps, weight_decay at model level
finegrain-ai/refiners pull request #227
Opened 2024-02-01 10:02 UTC by piercus

Related to #165 

I need to confirm that is working on real-life training run, but if you have any feedback in the meanwhile it would be great.

Especially, this implementation covers learning rate, betas, eps, weight_decay but we could do only learning rate, it will cover 99% of the needs.

2024-02-06 22:12 UTC, limiteinductive commented
Thanks for the PR; I'll have a look at it!

2024-02-08 10:45 UTC, limiteinductive commented
That's a great addition, let's rebase and then we can merge!

2024-02-08 15:57 UTC, limiteinductive reviewed
Could you rebase?

2024-02-08 16:22 UTC, piercus commented on src/refiners/training_utils/config.py
> +from torch.optim.optimizer import params_t as ParamsT
sry I don't get it

`from torch.optim.optimizer import ParamsT` not working

2024-02-08 16:28 UTC, limiteinductive commented on src/refiners/training_utils/config.py
> +from torch.optim.optimizer import params_t as ParamsT
or we could just write the Alias ourselves as `Params = Iterable[nn.Parameters] | Iterable[dict[str, Any]]

2024-02-08 18:10 UTC, piercus commented
@limiteinductive please review

2024-02-08 19:33 UTC, limiteinductive requested changes

2024-02-08 19:33 UTC, limiteinductive commented on src/refiners/training_utils/config.py
> +from torch.optim.optimizer import params_t as ParamsT
```suggestion
from torch.optim.optimizer import ParamsT
```

2024-02-08 21:10 UTC, deltheil commented on src/refiners/training_utils/config.py
> +from torch.optim.optimizer import params_t as ParamsT
OK, here is the thing re: this alias:

**PyTorch 2.1.0**

```python
params_t: TypeAlias = Union[Iterable[torch.Tensor], Iterable[Dict[str, Any]]]
```
See: [code](https://github.com/pytorch/pytorch/blob/v2.1.0/torch/optim/optimizer.py#L207)

**PyTorch 2.2.0**

```python
ParamsT: TypeAlias = Union[Iterable[torch.Tensor], Iterable[Dict[str, Any]]]
```
After this [PR](https://github.com/pytorch/pytorch/pull/111114)

2024-02-08 21:43 UTC, deltheil commented on src/refiners/training_utils/config.py
> +from torch.optim.optimizer import params_t as ParamsT
@piercus at this point in time we would prefer not enforcing PyTorch 2.2+ (see https://github.com/finegrain-ai/refiners/commit/7eb8eb4c68fa54cc86f043ecce5d1feed192b5ef). So I am afraid you should undo https://github.com/finegrain-ai/refiners/commit/553cd181f933e77921301cccd99242b8c334ddb8

- Option 1: poor man/not-so-great like:

```python
try:
    from torch.optim.optimizer import params_t as ParamsT  # PyTorch 2.1. TODO: remove "soon"
except ImportError as e:
    from torch.optim.optimizer import ParamsT
``` 

- Option 2: would be just write (inline) the type alias ourselves as suggested by @limiteinductive 

Any other options that come to mind? cc @limiteinductive

2024-02-08 21:55 UTC, limiteinductive commented on src/refiners/training_utils/config.py
> +from torch.optim.optimizer import params_t as ParamsT
not really, Option 2 doesn't work totally: this will create a type error when feeding it to the LRScheduler that expects the original type alias

2024-02-09 08:15 UTC, piercus commented on src/refiners/training_utils/config.py
> +from torch.optim.optimizer import params_t as ParamsT
Option 1 done in [b6c3d65](https://github.com/finegrain-ai/refiners/pull/227/commits/b6c3d654781e84b45a4587429a44180d304cdb10)

2024-02-09 09:28 UTC, deltheil approved these changes
Nice!

2024-02-09 09:29 UTC, deltheil commented on src/refiners/training_utils/config.py
> +from torch.optim.optimizer import params_t as ParamsT
Thanks Pierre!

2024-02-09 10:30 UTC, limiteinductive submitted a review, later dismissed

2024-02-09 10:34 UTC, deltheil commented
@piercus please have a look at the remaining points/suggestions! Then feel free to squash into a single commit (I can do it at merge time if you prefer) and we'd be good to go :)

2024-02-09 10:47 UTC, piercus commented
@deltheil squash done

2024-02-09 10:50 UTC, deltheil approved these changes

2024-02-09 11:05 UTC, merged