BaseBatch : easily manipulate
finegrain-ai/refiners pull request #304
Opened 2024-02-23 18:10 UTC by piercus

This is a proposal for a `Batch` class to be used when training.

## Context

When training, we always need to manipulate batched data, those data are generally Tensors (where batch_size is `shape[0]`) and lists (where batch_size is `len(lst)`)

Morever, it is quite classic to get mixed up between `list[Image.Image]` or `Tensor` that might repernsent the same thing (a group of images).

## Proposal

This BaseBatch class will both provide the ability to handle this easily, while provide type checks and size checks at different levels to raise the error as soon as possible in the process

### API

```python
from refiners.training_utils.batch import BaseBatch
from torch import Tensor

class MockBatch(BaseBatch):
    foo: Tensor
    bar: Tensor
    indices: list[int]
```
### Features

* Checking that hint are list or tensor when inherinting
* Making sure all the args have the same (non-zero) size
* Even if you do not use pyright, first-level-typing is checked when you inherit from `Batch`
* Training related features : `cls.collate`, `inst.to`, `cls.load`, `inst.save`
* Utilities like `__len__`, `__iter__`, `to_dict`, `clone`, `__eq__` ...

## Questions

* Currently Batch cannot have 0-size, this can be discussed.
* The `batch.py` and `test_batch.py` could also have been put in `training.py` and `test_training.py`, please share your thoughts
* There might be a second level PR for this, with jax-typed batch, but i feel this will not break the features of the current first version
* Not sure between `BaseBatch`, `AbstractBatch` or simply `Batch` as the top-level name

2024-02-25 17:28 UTC, limiteinductive commented on src/refiners/training_utils/batch.py
> +        return f"{self.__class__.__name__}({len(self)})[{','.join(attr_strs)}]"
Let's maybe be explicit about what is in the repr
```suggestion
        return f"{self.__class__.__name__}(size={len(self)})[{','.join(attr_strs)}]"
```

2024-02-25 18:25 UTC, limiteinductive requested changes
An issue is that you don't get a good signature when subclassing BaseBatch

![image](https://github.com/finegrain-ai/refiners/assets/82658997/127617f1-3191-48c3-a553-e7b030d25fdd)

2024-02-25 18:25 UTC, limiteinductive commented on src/refiners/training_utils/batch.py
> +        return collated_instance
```suggestion

    def __getattr__(self, name: str) -> AttrType:
        if name in get_type_hints(self.__class__):
            return getattr(self, name)
        else:
            raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")
            
    @classmethod
    def collate(cls: Type[T], batch_list: list[T]) -> T:
        collated_attrs: dict[str, Any] = {}
        type_hints = get_type_hints(cls)

        if len(batch_list) == 0:
            raise ValueError(f"Cannot collate an empty list of {cls.__name__}")

        for type_key in type_hints.keys():
            attr_list: list[Tensor | list[Any]] = [obj.__getattr__(type_key) for obj in batch_list]

            if all(isinstance(attr, Tensor) for attr in attr_list):
                tensor_tuple = cast(tuple[Tensor, ...], tuple(attr_list))
                collated_attrs[type_key] = cat(tensor_tuple, dim=0)
            else:
                collated_attrs[type_key] = [item for sublist in attr_list for item in sublist]

        collated_instance = cls(**collated_attrs)
        return collated_instance
```

2024-02-25 18:25 UTC, limiteinductive commented on src/refiners/training_utils/batch.py
> +        return collated_instance
You can probably also make a __setattr__ magic method

2024-02-26 13:29 UTC, piercus commented
@limiteinductive thanks for your help.

I've used [`@dataclass_transform()`](https://peps.python.org/pep-0681/) to fix the typing signature.

Also added `__add`, `__setattr__`

2024-02-26 14:11 UTC, limiteinductive commented on src/refiners/training_utils/batch.py
> +
```suggestion
            new_size = len(value) if isinstance(value, list) else value.shape[0]
```

2024-02-26 14:21 UTC, limiteinductive commented on src/refiners/training_utils/batch.py
> +
Otherwise you don't get correct typing
```suggestion
            attr_list = [obj.__getattr__(attr_name) for obj in batch_list]
```

2024-02-26 14:22 UTC, limiteinductive commented on src/refiners/training_utils/batch.py
> +    def attr_length(self, name: str) -> int:
shouldn't this be attr_size?

2024-02-26 14:23 UTC, limiteinductive commented on src/refiners/training_utils/batch.py
> +            args = {attr_name: getattr(self, attr_name)[i : i + 1] for attr_name in self.__class__.attr_types()}
```suggestion
        for i in range(len(self)):
```

2024-02-26 15:36 UTC, limiteinductive approved these changes
@deltheil PTAL

2024-04-11 10:13 UTC, closed without merging