⭐ Add example code for Stable Diffusion(1.5)
finegrain-ai/refiners pull request #409
Opened 2024-08-24 19:58 UTC by kadirnar

2024-08-24 20:09 UTC, kadirnar commented
How do I solve this error?
```bash
pip install pyright
rye run pyright
```

Error Message:
```
error: invalid or unknown script 'pyright' 
```

2024-08-26 08:28 UTC, catwell commented on src/refiners/foundationals/latent_diffusion/stable_diffusion_1/model.py
> +    sd15.lda.load_from_safetensors("realistic_vision.v5_1.sd1_5.autoencoder.safetensors")
```suggestion
    sd15.clip_text_encoder.load_from_safetensors("sd1_5.text_encoder.safetensors")
    sd15.unet.load_from_safetensors("sd1_5.unet.safetensors")
    sd15.lda.load_from_safetensors("sd1_5.autoencoder.safetensors")
```

2024-08-26 08:33 UTC, catwell requested changes

2024-08-26 08:33 UTC, catwell commented on src/refiners/foundationals/latent_diffusion/stable_diffusion_1/model.py
> +    sd15.lda.load_from_safetensors("realistic_vision.v5_1.sd1_5.autoencoder.safetensors")
```suggestion
    sd15.clip_text_encoder.load_from_safetensors("sd1_5.text_encoder.safetensors")
    sd15.unet.load_from_safetensors("sd1_5.unet.safetensors")
    sd15.lda.load_from_safetensors("sd1_5.autoencoder.safetensors")
```

2024-08-26 08:33 UTC, catwell commented on src/refiners/foundationals/latent_diffusion/stable_diffusion_1/model.py
> +    prompt = "RAW photo, face portrait photo of beautiful 26 y.o woman, cute face, wearing black dress, happy face, hard shadows, cinematic shot, dramatic lighting"
```suggestion
    prompt = "a cute cat, best quality, high quality"
    negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality"
```

2024-08-26 08:33 UTC, catwell commented on src/refiners/foundationals/latent_diffusion/stable_diffusion_1/model.py
> +        clip_text_embedding = sd15.compute_clip_text_embedding(text=prompt + ", best quality, high quality", negative_text="monochrome, lowres, bad anatomy, worst quality, low quality")
```suggestion
        clip_text_embedding = sd15.compute_clip_text_embedding(text=prompt, negative_text=negative_prompt)
```

2024-08-26 08:33 UTC, catwell commented on src/refiners/foundationals/latent_diffusion/stable_diffusion_1/model.py
> +        # SDXL typically generates 1024x1024, here we use a higher resolution.
```suggestion
```

2024-08-26 08:33 UTC, catwell commented on src/refiners/foundationals/latent_diffusion/stable_diffusion_1/model.py
> +    prompt = "RAW photo, face portrait photo of beautiful 26 y.o woman, cute face, wearing black dress, happy face, hard shadows, cinematic shot, dramatic lighting"
(let's not put too specific prompts in examples)

2024-08-26 08:33 UTC, catwell commented on src/refiners/foundationals/latent_diffusion/stable_diffusion_1/model.py
> +        # SDXL typically generates 1024x1024, here we use a higher resolution.
(This comes from [this guide](https://refine.rs/guides/adapting_sdxl/) but it does not concern this example.)

2024-08-26 08:33 UTC, catwell commented on src/refiners/foundationals/latent_diffusion/stable_diffusion_1/model.py
> +    sd15.lda.load_from_safetensors("realistic_vision.v5_1.sd1_5.autoencoder.safetensors")
(let's not use specific models in examples)

2024-08-29 22:42 UTC, kadirnar commented
I ran this code and there was no change. Can you review it again?
```bash
rye run pyright
```

2024-08-31 08:30 UTC, catwell approved these changes

2024-08-31 09:27 UTC, catwell commented
@kadirnar Can you squash all the commits into the first one?

I'd do it but with the way this repository is configured I cannot for external PRs like this one (because the main branch is protected and squash in the Git UI is disabled).

One way to do it is with interactive rebase, i.e. run `git rebase -i HEAD~10` and turn the last 5 commits into fixups like in the screenshot below, then force push to the branch.

![Screenshot from 2024-08-31 11-25-25](https://github.com/user-attachments/assets/a6ca5bc7-a2ac-4723-98d0-6bc79ea1ff6f)

2024-09-05 21:42 UTC, kadirnar commented
I rolled back the previous commits and fixed them manually. Can you check?

2024-09-06 07:16 UTC, merged

2024-09-06 07:16 UTC, catwell commented
It's merged, thanks!